### ISSUE TITLE
Add eddington number as a jersey

### ISSUE THREAD

**Issue by noelbruin** [brettch/shamvelo#9]

**Comment by brettch** [comment]
Come on, Bruisey.  There's a description field as well as a title ;-)

Should this Eddington number be calculated on a per year basis?

**Comment by noelbruin** [comment]
Eddington number it is defined as "the largest integer E, where you have cycled at least E miles on at least E days.

I think this should be part of only the Yearly target, or ideally use all your activities since you joined strava for a  "lifetime" number - but will be hard to shift the dial. Lets go yearly. Doing it weekly or monthly kinda doesn't make sense.

**Comment by noelbruin** [comment]
this kind of a future goal thing would be cool to add in as well:

eg:
You need 5 more days (of 36 miles or more) to achieve an Eddington number of 36
You need 10 more days (of 37 miles or more) to achieve an Eddington number of 37
You need 15 more days (of 38 miles or more) to achieve an Eddington number of 38
You need 18 more days (of 39 miles or more) to achieve an Eddington number of 39
You need 21 more days (of 40 miles or more) to achieve an Eddington number of 40
You need 41 more days (of 50 miles or more) to achieve an Eddington number of 50
You need 54 more days (of 60 miles or more) to achieve an Eddington number of 60
You need 69 more days (of 70 miles or more) to achieve an Eddington number of 70

**Comment by brettch** [comment]
The "Astrophysicist" jersey is now up on the board
